[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 5

[theme]
primaryColor = "#37352F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F6F3"
textColor = "#37352F"
