[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 5
# 防止长时间任务时 WebSocket 断连
enableWebsocketCompression = false
maxMessageSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#37352F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F6F3"
textColor = "#37352F"
